### ISSUE TITLE
Missing sources in src/lib

### ISSUE THREAD

**Issue by LadaF** [szaghi/StringiFor#10]
I am missing a lot of source files in src/lib which the makefile expects. For the HASTY test case I had to copy penf.F90 from the documentation page. Is this intentional?

**Comment by szaghi** [comment]
@LadaF 

yes, it is intentional. FoBiS is able to find the source everywhere :smile: However, I forget to update the makefile... sorry. 

### action => update makefile

**Comment by szaghi** [comment]
@LadaF In the new 0.9.2 version I have just amended the makefile, your manual copy is no more necessary if you want to use makefile (although FoBiS remains the official main building tool).

Thank you for pointing it out.
