### ISSUE TITLE
Internal error with VS 2015 and Intel Fortran 2017

### ISSUE THREAD

**Issue by PierreArchambeau** [szaghi/StringiFor#14]
Hi,
I would like to compile your very interesting module under windows and Intel Fortran 2017.
I have a "Catastrophic error" in the file "stringifor_string_t.F90".
Could you help me to resolve it?
Best regards,
Pierre

> Compiling with Intel(R) Visual Fortran Compiler 17.0.0.109 [Intel(R) 64]...
> stringifor_string_t.F90
> 010101_14277
> catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
> compilation aborted for D:\Programmation\wolf_oo\External_library\StringiFor-master\src\lib\stringifor_string_t.F90 (code 1)

**Comment by szaghi** [comment]
@PierreArchambeau 

Dear Pierre,

thank you for trying StringiFor.

This error sounds familiar, but I have not access to Windows, thus my help can be *partial*.

First of all, I obtain such an error when, in debug mode, I activate check-bounds: I do not why (looks like an Intel bug), but with `-check bounds` Intel Compiler generates such a catastrophic error. As you can see in my [fobos](https://github.com/szaghi/StringiFor/blob/master/fobos#L14) I had to disable such a check in debug mode.

Now, I cannot say if it is the same for you. Probably, you have to check your Visual Studio configuration for such a check. In Visual Studio you compile pressing a button, but you have also some predefined configurations for *release* and *debug* builds. Check those configurations (project settings, if I remember correctly) and disable check bounds.

Let me know if this helps or not.

My best regards.

**Comment by PierreArchambeau** [comment]
Dear szaghi,
Great !
All is fine without the bounds check.
Thanks alot for your reactivity.

**Comment by PierreArchambeau** [comment]
For information, I'm reporting this bug to Intel.

**Comment by szaghi** [comment]
@PierreArchambeau 

You are much more than welcome! 

Thank you very much for reporting it, I have not yet found the time to provide a minimal example reproducing the issue.

P.S. I you like, we are very happy if you join our group on Fortran here on GitHub, see [Fortran-FOSS-Programmers](https://github.com/Fortran-FOSS-Programmers).

My best regards.

**Comment by PierreArchambeau** [comment]
I would be happy to join the group, but how?

**Comment by szaghi** [comment]
@PierreArchambeau 

I have just invited you :smile:

**Comment by szaghi** [comment]
@PierreArchambeau 

Sorry, I just recalled now that another user has already opened a similar issue on Intel forum, see this

https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/673816

Steve Lionel said that this will be fixed in the incoming update2 of 2017.

**Comment by PierreArchambeau** [comment]
I posted the bug through the "Intel Business Portal", not the forum.
I updated and provided the link above. Maybe they will confirm the fix's date .
