### ISSUE TITLE
non-conformance in PURE internal procedure SPLIT_LAST_TOKEN

### ISSUE THREAD

**Issue by ThemosTsikas** [szaghi/StringiFor#16]
The NAG Fortran Compiler notices that:

Error: src/StringiFor/stringifor_string_t.F90, line 1551: TOKENS cannot be INTENT(OUT) actual arg in PURE procedure SPLIT_LAST_TOKEN

SPLIT_LAST_TOKEN is a PURE internal subroutine of PURE subroutine SPLIT_CHUNKED which has a TOKENS INTENT(OUT) dummy argument.  TOKENS is accessed in SPLIT_LAST_TOKEN by host association and is used as the TO actual argument of  MOVE_ALLOC which is INTENT(OUT).  That means TOKENS is used in a "variable definition context" which is expressly not allowed for host-association accessed entities.

The restriction is C1272 in "12.6 Pure procedures" of the 2003 Fortran Standard. The Final Committee Draft (FCD) of the new Standard (Fortran 2003) is available as PDF from http://www.dkuug.dk/jtc1/sc22/open/n3661.pdf

C1272 
In a pure subprogram any designator with a base object that is [...] accessed by [...] use association [...], shall not be used in the following contexts:
(1) In a variable deﬁnition context(16.5.7);

16.5.7 Variable deﬁnition context 
Some variables are prohibited from appearing in a syntactic context that would imply deﬁnition or un- deﬁnition of the variable (5.1.2.7, 5.1.2.12, 12.6). The following are the contexts in which the appearance of a variable implies such deﬁnition or undeﬁnition of the variable: 
[...]
(10) An actual argument in a reference to a procedure with an explicit interface if the associated dummy argument has the INTENT(OUT) or INTENT(INOUT) attribute

**Comment by szaghi** [comment]
Dear @ThemosTsikas 

Thank you very much for your feedback. This issue has passed silently with compilers (GNU and Intel). I'll fix it very soon.

Thank you very very much!

My best regards.

**Comment by szaghi** [comment]
Dear @ThemosTsikas 

I have fixed (I hope) this issue in the just uploaded 0.9.6 version. I simply passed `tokens` as an explicit argument `intent(inout)` instead of rely on host-association. My test suite passed, but I have not access to NAG: please, can you check with your compiler that this new version is standard conforming?

Thank you very much for your help, it is very appreciated.

**Comment by ThemosTsikas** [comment]
Dear @szaghi 

Yes, the file now passes with the following warnings

```
Warning: src/lib/stringifor_string_t.F90, line 468: Unused dummy variable SELF
Questionable: src/lib/stringifor_string_t.F90, line 1382: Variable FOUND set but never referenced
Warning: src/lib/stringifor_string_t.F90, line 1693: Unused dummy variable KIND
Warning: src/lib/stringifor_string_t.F90, line 1710: Unused dummy variable KIND
Warning: src/lib/stringifor_string_t.F90, line 1727: Unused dummy variable KIND
Warning: src/lib/stringifor_string_t.F90, line 1744: Unused dummy variable KIND
Warning: src/lib/stringifor_string_t.F90, line 1761: Unused dummy variable KIND
Warning: src/lib/stringifor_string_t.F90, line 1778: Unused dummy variable KIND
Warning: src/lib/stringifor_string_t.F90, line 1795: Unused dummy variable KIND
Warning: src/lib/stringifor_string_t.F90, line 2883: Unused dummy variable V_LIST
Warning: src/lib/stringifor_string_t.F90, line 3022: Unused dummy variable IOTYPE
Warning: src/lib/stringifor_string_t.F90, line 3022: Unused dummy variable V_LIST
Questionable: src/lib/stringifor_string_t.F90, line 254: LEN of deferred-length character object SELF%RAW in a specification expression
Questionable: src/lib/stringifor_string_t.F90, line 283: LEN of deferred-length character object SELF%RAW in a specification expression

```
I had to modify the makefile (to add NAG clause and because I cloned PENF in src/third_party)

>git diff makefile 
```
diff --git a/makefile b/makefile
index 13a1745..ef550bd 100644
--- a/makefile
+++ b/makefile
@@ -15,6 +15,12 @@ ifeq "$(COMPILER)" "intel"
   OPTSC = -c -assume realloc_lhs -standard-semantics -std08 -O2 -Dr16p -module $(DMOD)
   OPTSL = -O2 -module $(DMOD)
 endif
+ifeq "$(COMPILER)" "nag"
+  FC    = nagfor
+# nagfor has quad-precision (precision=31 range=291) but not the one demanded by r16p
+  OPTSC = -c -C=array -C=bits -C=calls -C=dangling -C=do -C=intovf -C=present -C=pointer -C=recursion -colour -fpp -f2008 -gline -info -kind=unique -mtrace -nan -O4 -I $(DMOD) -mdir $(DMOD)
+  OPTSL = -I $(DMOD)
+endif
 
 TESTS = no
 ifeq "$(TESTS)" "yes"
@@ -388,13 +394,12 @@ $(DOBJ)stringifor_string_t.o: src/lib/stringifor_string_t.F90 \
        @echo $(COTEXT)
        @$(FC) $(OPTSC)  $< -o $@
 
-$(DOBJ)penf.o: src/third_party/BeFoR64/src/lib/penf.F90 \
+$(DOBJ)penf.o: src/third_party/PENF/src/lib/penf.F90 \
        $(DOBJ)penf_global_parameters_variables.o \
        $(DOBJ)penf_b_size.o \
        $(DOBJ)penf_stringify.o
        @echo $(COTEXT)
        @$(FC) $(OPTSC)  $< -o $@
-       @rm -f $(DOBJ)penf_global_parameters_variables.o $(DOBJ)penf_b_size.o $(DOBJ)penf_stringify.o
 
 $(DOBJ)befor64_pack_data_m.o: src/third_party/BeFoR64/src/lib/befor64_pack_data_m.F90 \
        $(DOBJ)penf.o

```

**Comment by szaghi** [comment]
Dear @ThemosTsikas 

Thank you very much.

Some unused arguments are indeed used for "dynamic dispatching" in generic interfaces. Others, simply have not captured by compiler :cry: 

NAG diagnostics rocks!

Thank you for sharing your makefile, I'll add it in the next release: I did not insert it before because I have not access to NAG.

See you soon.

My best regards.

P.S. I'll left this open until I have checked all unused variables and added your NAG configs in the makefile.

**Comment by szaghi** [comment]
Dear @ThemosTsikas 

I have check all the remaining warnings. I have fixed all except 

```shell
Warning: src/lib/stringifor_string_t.F90, line 2883: Unused dummy variable V_LIST
Warning: src/lib/stringifor_string_t.F90, line 3022: Unused dummy variable IOTYPE
Warning: src/lib/stringifor_string_t.F90, line 3022: Unused dummy variable V_LIST
```

because DTIO is not yet completed. 

The unused KIND will not fixed because it is a false positive: I used KIND argument only for the dynamic dispatching disambiguation of generic interfaces. 

I have also updated the makefile.

Thank you very very much!

My best regards.
