### ISSUE TITLE
Compiler Error with intel compiler

### ISSUE THREAD

**Issue by shookware** [szaghi/StringiFor#19]
When I use intel compiler, it reports there are some errors. when I revert an old commit "50cb0b00d00374b6bb56e9b2cee97576b28830de", it has no error.
When I use gfortran 7.1 compiler, the latest commit also has no error.
my platform is Mac OS.

> src/lib/stringifor_string_t.F90(4107): warning #5268: Extension to standard: The text exceeds right hand column allowed on the line.
>    character(len(iomsg))                    :: local_iomsg    !< Local variant of iomsg, so it doesn't get inappropriately redefined.
> ------------------------------------------------------------------------------------------------------------------------------------^
> src/lib/stringifor_string_t.F90(3809): error #7508: A specification function must be a pure function.   [LEN]
>    character(len=len(iomsg))                :: local_iomsg !< Local variant of iomsg, so it doesn't get inappropriately redefined.
> -----------------^
> src/lib/stringifor_string_t.F90(4030): error #7508: A specification function must be a pure function.   [LEN]
>    character(len(iomsg))                    :: local_iomsg  !< Local variant of iomsg, so it doesn't get inappropriately redefined.
> -------------^
> src/lib/stringifor_string_t.F90(4077): error #7508: A specification function must be a pure function.   [LEN]
>    character(len(iomsg))                    :: local_iomsg !< Local variant of iomsg, so it doesn't get inappropriately redefined.
> -------------^
> src/lib/stringifor_string_t.F90(4107): error #7508: A specification function must be a pure function.   [LEN]
>    character(len(iomsg))                    :: local_iomsg    !< Local variant of iomsg, so it doesn't get inappropriately redefined.
> -------------^
> compilation aborted for src/lib/stringifor_string_t.F90 (code 1)

**Comment by szaghi** [comment]
I have currently no issue in compiling with Intel Fortran, I am closing this issue, feel free to reopen it if needed.

Cheers
