### ISSUE TITLE
Support Defined I/O for GCC Fortran >= 7.x.y

### ISSUE THREAD

**Issue by band-a-prend** [szaghi/StringiFor#20]
The [StringiFor/README.md](https://github.com/szaghi/StringiFor/blob/master/README.md) states:

> GNU partial support
> * GNU gfortran does not support user-defined-type-IO, thus some class features are disabled if GNU is used.

At the same time the [GCC 7 Releas Notes](https://gcc.gnu.org/gcc-7/changes.html) notify that 

> Fortran
> ...
> * User-defined derived-type input/output (UDTIO) is added.

Is it possible to enable the user-defined-type-IO features of StringiFor library for GNU GCC >= 7.x.y ?

Some tests are required also after enabling feature as I saw the examples of UDTIO for Intel Fortran Compiler that were not fully compatible for GNU GCC and that required some modifications before working correctly.

**Comment by szaghi** [comment]
Hi,

thank you for your patience. 

I am now back to the office. I'll try to reintroduce UDTIO support in the next days/weeks, stay tuned.

**Comment by band-a-prend** [comment]
If I make replacement 
`sed -i "s/#ifndef __GFORTRAN__/#if !(__GNUC__ < 7)/g"` 
for `/src/lib/stringifor_string_t.F90` file 
then StringiFor successfully compiles with gfortran 7.3.0 and at least example https://github.com/szaghi/StringiFor#basic-io build and give output: 
```
Hello World
Hello World
Hello World
```
Sorry, I can't test compilation with IFC after applying this patch.

**Comment by szaghi** [comment]
Defined IO integrated, I am closing this, but feel free to reopen if needed.

Cheers
