### ISSUE TITLE
Implement public method to convert character to string

### ISSUE THREAD

**Issue by epagone** [szaghi/StringiFor#22]
There are situations when it doesn't make sense to create a `type(string)` variables only to pass its content to a procedure.

E.g. in this context

```
type foo
  type(string)  :: name
contains
  procedure, public :: foo_set_name
end type foo

subroutine foo_set_name(self, name)
  class(foo), intent(inout) :: self
  type(string), intent(in)  :: name
  
  self%name = name
end subroutine foo_set_name
```
the following throws an argument type mismatch error

```
...
type(foo) :: bar

call bar%foo_set_name("baz")
...
```

It would be nice to have a method converting a character variable to string.

**Comment by szaghi** [comment]
Hi @epagone 

sorry for the delay, I am very busy.

You are right, I have to overload the *string* name in order to create a string on the fly, I missed it, thank you for pointing it out!

Tomorrow I hope to implement it.

Stay tuned.

**Comment by szaghi** [comment]
@epagone 

Hi, I have just uploaded a new release with an *on-the-fly* method to create string by means of character without need to declare a temporary string. I just overloaded the `string` name with such a function, so your snippet should look like the following:

```fortran
type(foo) :: bar

call bar%foo_set_name(string("baz"))
```
Note that `baz` character must be passed to the *on-the-fly* creator `string`.

Please, let me know if this work for you.

My best regards.

**Comment by epagone** [comment]
Perfect! Thank you very much @szaghi for finding the time in your super-busy schedule. I love `stringifor` and I think that I have uncovered some other bugs with automatic allocation and reallocation on assignment of allocatable arrays of strings. However, I don't know if it's more a gfortran issue as I cannot really test on ifort. Once I'll make sure it's a `stringifor` problem, I'll open a new issue report.

Most importantly, I'll let you know if your new version of `stringifor` works for me as soon as possible. Thanks again and I hope your fantastic projects are only on hold and you'll have time to resume development some time in the near future.

Cheers!

**Comment by szaghi** [comment]
Thanks your help in finding bugs, it is very appreciated.

Yes, this year has been very busy, next year I  should be able to restart with Fortran with new energy and much more time.

Looking forward for your feedback.

**Comment by epagone** [comment]
Hi @szaghi 

I'm sorry for the very long delay. I had to fight for the update of `FoBiS` and the recompilation of the updated `StringiFor` that were quite painful in my system where 4 different versions of `gfortran` and two major versions of `python` coexist. The "icing on the cake" was GitHub not accepting (for the second time in a few weeks) my correct credentials at login that, then, I had to reset.

However, rant aside, I am very happy because the new version of `StringiFor` works like a charm in solving the reported issue. Many many thanks again! Closing.

**Comment by szaghi** [comment]
@epagone I am sorry to heard the troubles with FoBiS, but I am happy for StringiFor!

Thank you very much for your feedback!

Cheers.

**Comment by epagone** [comment]
@szaghi just for the records: I really appreciate your work on `FoBiS`. The issue (now resolved) was just caused by the coexistence of different versions of `python` and `gfortran` on my system. Thanks for your efforts again: you are one of the few talented and brave programmers that keep modern Fortran usable and alive!

**Comment by szaghi** [comment]
@epagone you are too much kind!
