### ISSUE TITLE
make TESTS=yes does not run

### ISSUE THREAD

**Issue by epagone** [szaghi/StringiFor#25]
I cannot compile with FoBiS because of [this issue](https://github.com/szaghi/FoBiS/issues/111).

GNU make works ok
```
$ make
Compile stringifor_string_t.F90
Compile stringifor.F90
Assemble STRINGIFOR
```
but does not run the tests
```
$ make TESTS=yes
make: *** No rule to make target 'src/tests/is_real.f90', needed by 'exe/obj/is_real.o'. Stop.
```

Please note that I want to use gfortran 9.1 installed on my machine and available through `gfortran-9` from my command line. Thus, I have edited my `makefile`
```
$ cat makefile | head
#!/usr/bin/make
MAKEFLAGS = -j 1

#main building variables
DSRC = src

COMPILER = gnu
ifeq "$(COMPILER)" "gnu"
  FC    = gfortran-9
  OPTSC = -c -frealloc-lhs -std=f2008 -fall-intrinsics -O2 -D_R16P_SUPPORTED -J $(DMOD)
```
Is this edit that triggers the problem?

**Comment by szaghi** [comment]
@epagone 

the issue of FoBiS will be checked soon.

Concerning the GNU make instead, the makefile is simply too old and unmaintained. I have to check, but surely many of the old tests are now written as *doctests* by means of FoBiS, thus simply that GNU make rule is trying to compile files that do not exist any more.

**Comment by szaghi** [comment]
@epagone can this be closed?

**Comment by epagone** [comment]
Up to you. If you want to claim build support for GNU make, I would say this is still a problem. In other words, make TESTS=yes still does not run, but there are other methods to build StringiFor that work. It's your call.

**Comment by szaghi** [comment]
@epagone sorry, I re-read more carefully the issue: yes, I do not support GNU Make anymore, at least for what concerns the tests, so yes, this issue cannot be fixed by me. Anyway, I will accept PR for maintain GNU Make support
