### ISSUE TITLE
Create a string on the fly from a real or integer number

### ISSUE THREAD

**Issue by epagone** [szaghi/StringiFor#27]
Thanks to the fix in [this issue](https://github.com/szaghi/StringiFor/issues/22) I can now do
```fortran
type foo
  type(string)  :: name
contains
  procedure, public :: foo_set_name
end type foo

subroutine foo_set_name(self, name)
  class(foo), intent(inout) :: self
  type(string), intent(in)  :: name
  
  self%name = name
end subroutine foo_set_name

call bar%foo_set_name(string("baz"))
```
Would it be possible to allow also
```fortran
call bar%foo_set_name(string(42._r8p))
call bar%foo_set_name(string(123))
```
Currently, `gfortran-9` complains
```
Error: Component ‘raw’ at (1) is a PRIVATE component of ‘string’
```

**Comment by szaghi** [comment]
Hi, I am sorry but I am currently out of office for .my holiday, I will come back at the end of August. As soon as possible I will keep this issue on.

Cheers

**Comment by szaghi** [comment]
Dear @epagone , please note the following:

+ assignments are already overloaded, thus you can already assign integer and real to a string without any efforts (see the complete example below):
+ to allow the LHS reallocation of the other issue I had to make public the member `raw`, now you can do what ever you want with it.

Than said, please consider the following example that I hope cover your scenario:

```fortran
module foo_type
use stringifor
implicit none

type foo
   type(string) :: name
contains
   generic, public :: set_name => set_name_s, set_name_c, set_name_i, set_name_r
   procedure       :: set_name_s
   procedure       :: set_name_c
   procedure       :: set_name_i
   procedure       :: set_name_r
end type foo

contains
   subroutine set_name_s(self, name)
   class(foo),   intent(inout) :: self
   type(string), intent(in)    :: name

   self%name = name
   endsubroutine set_name_s

   subroutine set_name_c(self, name)
   class(foo),   intent(inout) :: self
   character(*), intent(in)    :: name

   self%name = name
   endsubroutine set_name_c

   subroutine set_name_i(self, name)
   class(foo), intent(inout) :: self
   integer,    intent(in)    :: name

   self%name = name
   endsubroutine set_name_i

   subroutine set_name_r(self, name)
   class(foo), intent(inout) :: self
   real,       intent(in)    :: name

   self%name = name
   endsubroutine set_name_r
endmodule foo_type

program set_name
   use foo_type
   use stringifor
   implicit none

   type(foo)    :: bar
   type(string) :: baz

   baz = "baz"
   call bar%set_name(baz)
   print*, bar%name
   call bar%set_name("baz")
   print*, bar%name
   call bar%set_name(123)
   print*, bar%name
   call bar%set_name(1.23)
   print*, bar%name

endprogram set_name
```

I have compiled with GNU Fortran 9 and upon execution I obtain:

```bash
┌╼ stefano@zaghi(10:11 AM Thu Oct 24) on develop [?]
├───╼ ~/fortran/StringiFor 18 files, 196Kb
└──────╼ ./exe/set_name 
 baz
 baz
 +123
 +0.123000E+01
```

Note that strings can be easily initialized with numbers because the assignment operator `=` is overloaded.

Let me know if this is enough for your scenario.

**Comment by epagone** [comment]
Many thanks again for spending time on my issue @szaghi! I admit that what you suggest is a suboptimal solution since it requires quite a bit of code duplication but I think this has more to do with the limitations of the language rather than your beautiful library and there is little more than you can do.

In my use case I have a rather lengthy initialisation subroutine where I do not simply set the name and that would make the code duplication unpleasant. I think that I will resort nesting the generic `set_name` within a single initialisation method to minimise the "damage" (in terms of verbosity).

One more time, thanks for keeping Fortran alive with your invaluable work!
