### ISSUE TITLE
split

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/StringiFor#5]
I've got some code somewhere I wrote a while back that implements a [split()](http://www.tutorialspoint.com/python/string_split.htm) function. If you're interested, I can add this.

**Comment by szaghi** [comment]
@jacobwilliams your help is always welcome. Indeed, the split method should be already here, https://github.com/szaghi/StringiFor/blob/master/src/lib/stringifor.F90#L365 

It should work https://github.com/szaghi/StringiFor/blob/master/src/tests/split.f90

However I will study your implementation with interest if you paste it here.

Thank uou very much!

P.S. I redirect a fortraner interested to DAG to you, I hope to not hurt you.

**Comment by jacobwilliams** [comment]
Oh, I didn't see that you already had it. I'll find mine and see if they are doing the same thing.
