### ISSUE TITLE
cannot compile with GNU Fortran version 5.4.0 

### ISSUE THREAD

**Issue by zhouguidi** [szaghi/StringiFor#9]
Hi,

Trying to compile StringiFor on Ubuntu 16.04 (64-bit) using gfortran version 5.4.0 fails with the following message:

f951: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-5/README.Bugs for instructions.

using standard FoBiS.py build.

Cheers,
Guidi

**Comment by szaghi** [comment]
This is a known issue, but I faced with it only compiling in fully debug mode with Intel Compiler 16.x...

I want to fix it definitely, but I am not sure about the time (currently I have not access to GNU 5.4). In the meanwhile can you report the whole statement you use to compile StringiFor? Are you using FoBiS?

Thank you very much for your help!

**Comment by zhouguidi** [comment]
Yes, after a fresh git clone --recursive, immediately do FoBiS.py build. Also tried FoBiS.py build -mode stringifor-shared-gnu but the result is the same.

**Comment by szaghi** [comment]
Dear @zhouguidi ,

I am very sorry, but I cannot fix this issue. I have done some tests and I can confirm that this is a bug of GNU gfortran 5.4. I cannot reproduce this bug with a minimal working example, thus I cannot submit a request to fix to GNU gfortran team. 

The only thing that I can do is to clarify in the documentation that only GNU gfortran 6.x can compile StringiFor. I am very sorry, but this is the best that I can do.

See you soon.
